Added friendlier message when shell file is not found.

diff --git a/lib/dependency/dependency b/lib/dependency/dependency
--- a/lib/dependency/dependency
+++ b/lib/dependency/dependency
@@ -4,16 +4,23 @@
 currentdir=$PWD
 filename=$(basename "$0")
 args="$@"
-outpath=$(node -pe "JSON.parse(process.argv[1]).spypkg.projectOutPath" "$(cat $currentdir/package.json)")
-adaptorfullpath=$(realpath $currentdir/$outpath/$filename-adaptor.js)
 
-if [ ! -f "$adaptorfullpath" ]; then
-  adaptorfullpath=$(realpath $currentdir/$outpath/adaptor.js)
+if [ -f $currentdir/package.json ]; then
+  outpath=$(node -pe "JSON.parse(process.argv[1]).spypkg.projectOutPath" "$(cat $currentdir/package.json)")
+  adaptorfullpath=$(realpath $currentdir/$outpath/$filename-adaptor.js)
+
+  if [ ! -f "$adaptorfullpath" ]; then
+    adaptorfullpath=$(realpath $currentdir/$outpath/adaptor.js)
+  fi
+
+  echo "[spypkg] Executing: node " "$adaptorfullpath" "$filename $@"
+  node "$adaptorfullpath" "$filename $@"
+
+  ret=$?
+
+  exit $ret
+else
+  echo "'spypkg' was unable to load 'package.json' in the current directory for '"$filename"' command."
+  echo "Remove the following file if not needed: "$0
+  exit 1
 fi
-
-echo "[spypkg] Executing: node " "$adaptorfullpath" "$filename $@"
-node "$adaptorfullpath" "$filename $@"
-
-ret=$?
-
-exit $ret
