Added shell script catch when out dir is not found.

diff --git a/lib/dependency/dependency b/lib/dependency/dependency
--- a/lib/dependency/dependency
+++ b/lib/dependency/dependency
@@ -8,14 +8,21 @@ args="$@"
 
 if [ -f $currentdir/package.json ]; then
   outpath=$(node -pe "JSON.parse(process.argv[1]).spypkg.projectOutPath" "$(cat $currentdir/package.json)")
-  adaptorfullpath=$(realpath $currentdir/$outpath/$filename-adaptor.js)
-
-  if [[ "$outpath" = "" ]]; then
+  
+  if [ "$outpath" = "" ]; then
     echo "'spypkg' was unable to find 'projectOutPath' property in 'package.json' for '"$filename"' command."
     echo "Remove the following file if not needed: "$0
     exit 1
   fi
-  
+
+  if [ -d "$currentdir/$outpath" ]; then
+    adaptorfullpath=$(realpath $currentdir/$outpath/$filename-adaptor.js)
+  else
+    echo "'spypkg' was unable to find '$outpath' directory."
+    echo "Remove the following file if not needed: "$0
+    exit 1
+  fi
+
   if [ ! -f "$adaptorfullpath" ]; then
     adaptorfullpath=$(realpath $currentdir/$outpath/adaptor.js)
   fi
